### ISSUE TITLE
App startup with only blank background and menu.

### ISSUE THREAD

**Issue by ray1997** [nrcrast/DbdPerkTool#2]
I assume that the app is unable to locate the game folder as I installed the game else where, not on Steam folder in C:\ drive

**Comment by nrcrast** [comment]
That's interesting. It tries to get the info about the install location from Steam using the Win registry. I've yet to test it with a custom install path. There is some logic in there to fail gracefully if it cannot find dead by daylight, but I've only tested that in a situation where the game wasn't installed at all. Let me see if I can get you a debug build so we can get a stack trace, or maybe the time would be better spent putting some "log file" code in there.

**Comment by ray1997** [comment]
Ok, sure.

**Comment by ray1997** [comment]
It's appear to be the issue resolved itself, not sure when, but it's working now.
