### ISSUE TITLE
Error installing pack

### ISSUE THREAD

**Issue by Nekoboro** [nrcrast/DbdPerkTool#20]
Hi!
I keep having an issure when I try to install any pack. 
I've checked my game files via Steam and all, uninstalled and reinstalled Dead By Daylight Icon Toolbox but it's still the same.
![Untitled 2](https://user-images.githubusercontent.com/68041471/86990852-e1c48380-c19d-11ea-931e-5ce22c7e471b.png)

I don't know what to do anymore...

**Comment by nrcrast** [comment]
Hmmm where are you located?

**Comment by nrcrast** [comment]
What happens if you download the zip directly from here and unzip it yourself?

https://files.dbdicontoolbox.com/file/dbd-icon-toolbox/Yoinks-Entity's-Realm.zip

**Comment by Nekoboro** [comment]
I'm from Belgium and the zip gives me "error network" but my connection is fine atm :/

**Comment by nrcrast** [comment]
The zip downloads alright for me, so I think that's the root of the problem. We need to figure out why it's not working for you. Can you try from a different browser or a private window? Do you have a different computer you can try? Could be some sort of network configuration error.

**Comment by nrcrast** [comment]
Could you paste a screenshot of your browser when you try to download that zip?

**Comment by Nekoboro** [comment]
Oh I believe you, I must have done something wrong I guess, I tried on Chrome, Firefox and Edge, still the same.
My screenshot is not going to be a great help I'm afraid 
![Untitled 2](https://user-images.githubusercontent.com/68041471/86991915-8cd63c80-c1a0-11ea-9ffa-2235f288fc85.png)

**Comment by nrcrast** [comment]
I switched to a different hosting provider a week or so ago and I've been getting intermittent problems like this from people in certain countries. Could you try the following:
1.) Open chrome
2.) Open a new tab
3.) Press ctrl + shift + i to open the developer tools
4.) Go to the "Network" tab
5.) Paste https://files.dbdicontoolbox.com/file/dbd-icon-toolbox/Yoinks-Entity's-Realm.zip into the url bar of that tab

And then send me a screenshot of the network traffic? It will look something like this, except you'll have some sort of failure
![image](https://user-images.githubusercontent.com/5086301/86992769-3a7d2780-c170-11ea-8b71-b1874ebc36f2.png)

**Comment by Nekoboro** [comment]
It worked, I don't know how but the file downloaded this time.
I hope that is the screen that you wanted, I was kinda lost I'm sorry (and I don't want to waste your time).
Sooo at least I have the file now :)
![Untitled 2](https://user-images.githubusercontent.com/68041471/86993418-41be2880-c1a4-11ea-9a7d-db2c318cfe94.png)

**Comment by nrcrast** [comment]
Can you try again but click on this row in the results:
![image](https://user-images.githubusercontent.com/5086301/86993992-559d6680-c173-11ea-8789-37236a958583.png)

**Comment by Nekoboro** [comment]
![Untitled 2](https://user-images.githubusercontent.com/68041471/86994238-366bfc80-c1a6-11ea-83ce-73b08d1e3ff9.png)
![Untitled 3](https://user-images.githubusercontent.com/68041471/86994294-54396180-c1a6-11ea-82e4-de97c8a88001.png)
Is that okay? Did not get well this time.

**Comment by nrcrast** [comment]
@Nekoboro Sorry I lost track of this thread. Are you still having troubles with the tool?

**Comment by Nekoboro** [comment]
Hello! I Since I removed my wifi and wired my PC on ethernet everything is fine, thank you for your help. :)
