### ISSUE TITLE
"Help" menu should link to this project instead of electron project

### ISSUE THREAD

**Issue by ray1997** [nrcrast/DbdPerkTool#3]
Learn more > Remove this?
Documentation > https://nrcrast.github.io/DbdPerkTool/ ??
Community Discussion > Discord server?
Search Issues > this git project? https://github.com/nrcrast/DbdPerkTool/issues ?

**Comment by nrcrast** [comment]
Good catch. I kind of want to get rid of that menu bar entirely.

**Comment by nrcrast** [comment]
The help menu doesn't show up normally in the tool -- it was only showing up for you because something was going wrong during early initialization. Closing this one since fixing #2 will fix this as well.
