### ISSUE TITLE
Let users set favourite packs

### ISSUE THREAD

**Issue by Nereuxofficial** [nrcrast/DbdPerkTool#33]
Title pretty much says it. Let users save their favourite packs to set them faster und not have to search for them

**Comment by nrcrast** [comment]
@Nereuxofficial This has been a thing for awhile -- you just have to sign into the tool to use the feature since the packs are saved to your account. If you sign in, you'll see a star next to each pack and you'll have an option at the top to show only your favorites.

**Comment by Nereuxofficial** [comment]
My bad, but you should probably update the link to the installer on the website, it seems to be outdated.

**Comment by nrcrast** [comment]
@Nereuxofficial Oh snap you're right -- ancient.
