### ISSUE TITLE
Dead by Daylight Install Path

### ISSUE THREAD

**Issue by grii99** [nrcrast/DbdPerkTool#40]
I own Dead by Daylight on PC through Xbox game pass on PC. Does that matter when trying to install packs? Is this website only used for steam? It says "set your installation location via the settings tab." What are you supposed to put in the dead by daylight install path, then?

**Comment by Synidecrt** [comment]
Yeah I got it from the Microsoft store on PC too. I want to know if it would work. Will it scan the PC for the game files or do I have to set the location for it to install?

**Comment by MrJones6** [comment]
If you’ve installed Dead By Daylight from the Windows Store, you will be unable to use this tool. Windows store seems to install applications as read only, so there’s no way to use custom perks. [Source](https://dbdicontoolbox.com/)

**Comment by nrcrast** [comment]
Correct. No way to get custom icons on any install except for Steam. Sorry!
