### ISSUE TITLE
Individual perk selection/swapping

### ISSUE THREAD

**Issue by IndigoBlaze** [nrcrast/DbdPerkTool#46]
Sometimes I like a few perks in a pack, but only want to use one or two of them.
Sometimes I want to use a certain perk's icon on different perk. 

Not sure how difficult this would be, but having an index menu showing every perk and what their currently installed icon is would be nice!

**Comment by nrcrast** [comment]
@IndigoBlaze You can already select which exact icons you want when you install a pack. Are you talking about something else?

**Comment by IndigoBlaze** [comment]
To be more specific, if a pack has an icon for Bond and an icon for Leader, I want to only install the icon for Bond and NOT Leader. 

And then, with the same pack with icons for Bond and Leader, I want to be able to use the icon made for Bond in place of Leader, and vice versa. 

If these are actually already possible, let me know because I could very much just be stupid here XD
