### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ParksAndRekt** [nrcrast/DbdPerkTool#50]
When i go to install a pack, an error comes up saying "Error installing pack. Please set your installation location via the settings tab." but im not seeing that anywhere in the settings tap.
![DBD Toolbox](https://user-images.githubusercontent.com/86688317/123863300-6a7c8800-d8f7-11eb-9248-9c4b3835fa84.PNG)

**Comment by DoctorStoneza** [comment]
My dbd toolbox has the same error.

**Comment by iagoSsa** [comment]
i have the same problem :(((

**Comment by timpatullock** [comment]
Hey folks, just checking but under your settings within DBD Toolbox, is the "Dead By Daylight Install Path" set to the correct location?

![image](https://user-images.githubusercontent.com/5308823/129193004-61d54e66-9be7-4f40-a905-e8185db82f9d.png)
