### ISSUE TITLE
Some icon replacement, not a whole pack

### ISSUE THREAD

**Issue by ray1997** [nrcrast/DbdPerkTool#7]
It should be a new page and listing all the icons in the game.

Each icon will show how many alternate version it have and you can replace only that one icon.

There are lots of icon customization out there that only willing to do just one or few icons like this: https://www.reddit.com/r/PerkByDaylight/comments/ghwn56/sticker_i_use_as_decisive_strike/
or this: https://www.reddit.com/r/PerkByDaylight/comments/geqsyn/attack_on_titan_mikasa_resilience_bw_version/

**Comment by nrcrast** [comment]
Done in 1.1.5
