### ISSUE TITLE
Creator profile issue: Can't view notification if added others link

### ISSUE THREAD

**Issue by ray1997** [nrcrast/DbdPerkTool#80]
I'm still stuck using 1366×768 screen. I only added 2 links into my creator profile and a notifications area just got push further down with no way to scroll down to its.

![image](https://user-images.githubusercontent.com/14814401/156236833-53a50306-1402-4ca5-a212-e660ae785b92.png)

**Comment by nrcrast** [comment]
Ooooooooo CSS gross

**Comment by nrcrast** [comment]
TBH I might just add a totally separate notifications page. I think I added here out of laziness in the first place

**Comment by nrcrast** [comment]
Closed as a separate page was added
